#!/usr/bin/env bash

echo "- merging device files"
cat "net.js"              \
    "netfs.js"            \
  > "atomos-dev.js"

#docs
DOCNGN=`which jsdog`

if [ -n "$DOCS" ] && [ -n "$DOCNGN" ]
then
    echo "  - building documentation and unit tests"

    DOCDIR="../docs/device-files"
    DOCTMPL="-m ../docs/jsdog.jade"

    $DOCNGN $DOCTMPL -s net.js         -t t/net.js         > $DOCDIR/net.html
    $DOCNGN $DOCTMPL -s netfs.js       -t t/netfs.js       > $DOCDIR/netfs.html

else
    echo "  - skipping documentation and unit tests"
fi
