#!/usr/bin/env bash

cat "class.js"           \
    "assert.js"          \
    "guid.js"            \
    "bus.js"             \
    "stream.js"          \
    "file.js"            \
    "jsfs.js"            \
    "domfs.js"           \
    "process.js"         \
    "wash.js"            \
    "panel.js"           \
    "window.js"          \
    "commandwindow.js"   \
    "editwindow.js"      \
    "test.js"            \
  > "atomos-hx.js"
