#!/usr/bin/env bash

cd ./bin
./build

cd ../hx
./build

cd ..

#TODO zepto.eof.txt should not be required, check minifier & zepto issues on github

cat "vendor/zepto.min.js"   \
    "zepto.eof.txt"         \
    "vendor/ejohn-class.js" \
    "bin/atomos-bin.js"     \
    "hx/atomos-hx.js"       \
    "main.js"               \
  > "atomos.js"
