#!/usr/bin/env bash

echo "Atomic OS Build Utility"
echo ""

cd ./bin
./build

cd ../hx
./build

cd ..

#TODO zepto.eof.txt should not be required, check minifier & zepto issues on github

echo "- merging dependencies and wash commands into system"
cat "vendor/zepto.min.js"   \
    "zepto.eof.txt"         \
    "vendor/ejohn-class.js" \
    "system.js"             \
    "bin/atomos-bin.js"     \
    "hx/atomos-hx.js"       \
  > "atomos.t.js"

echo "- adding main"
cat "atomos.t.js" "main.js" > "atomos.js"

MINNGN=`which uglifyjs`
if [ -n "$MINNGN" ]
then
    echo "- minimizing"
    $MINNGN -o atomos.min.js atomos.js
else
    echo "- skipping minification"
fi

echo ""
